openapi: 3.0.2
info:
  title: PQ API v2
  version: 2021.06.17
  contact:
    email: support@payquicker.com
    url: 'https://www.payquicker.com'
    name: PayQuicker Support
  description: desc
  termsOfService: 'https://www.payquicker.com'
servers:
  - url: 'https://platform.mypayquicker.build/api/v2'
    description: ''
paths:
  '/accounts/{acct-token}/receipts':
    get:
      summary: List Account Receipts
      operationId: get-accounts-receipts
      description: |
        [Retrieve a list](page:working-with-resources/receipts#list-account-receipts) of all account(s) receipts that supports filtering, sorting, and pagination through existing mechanisms.'
      tags:
        - Receipts
      security:
        - client Credential Grant Flow:
            - read-only
  '/payments/{pmnt-token}':
    get:
      summary: Retrieve Payment
      operationId: get-payments-pmnt_token
      description: 'Retrieve a list of all payments that supports filtering, sorting, and pagination through existing mechanisms.'
      tags:
        - Payments
      security:
        - client Credential Grant Flow:
            - read-only
    post:
      summary: Accept Payment Quote
      operationId: post-payments-pmnt_token
      description: Accept an open payment quote.
      tags:
        - Payments
      security:
        - client Credential Grant Flow:
            - modify
    delete:
      summary: Cancel Payment Quote
      operationId: delete-payments-pmnt_token
      tags:
        - Payments
      description: Cancel an open payment quote.
      security:
        - client Credential Grant Flow:
            - modify
  '/payments/{pmnt-token}/retract':
    put:
      summary: Retract Payment (Full)
      operationId: put-payments-pmnt_token-retract
      tags:
        - Payments
      description: Perform a payment retraction for the full payment amount.
      security:
        - client Credential Grant Flow:
            - modify
    patch:
      summary: Retract Payment (Partial)
      operationId: patch-payments-pmnt_token-retract
      tags:
        - Payments
      description: Perform a payment retraction for a partial payment amount.
      security:
        - client Credential Grant Flow:
            - modify
  '/spend-back/{spnd-token}':
    get:
      summary: Retrieve Spendback
      operationId: get-spendback-spnd_token
      tags:
        - Spend Back
      description: Retrieve a single spendback quote using the spendback token.
      security:
        - client Credential Grant Flow:
            - read-only
    post:
      summary: Accept Spendback Quote
      operationId: post-spendback-spnd_token
      tags:
        - Spend Back
      description: Accept an open spendback quote. 
      security:
        - client Credential Grant Flow:
            - modify
    delete:
      summary: Cancel Spendback Quote
      operationId: delete-spendback-spnd_token
      tags:
        - Spend Back
      description: Cancel an open spendback quote. 
      security:
        - client Credential Grant Flow:
            - modify
  '/spend-back/{spnd-token}/refund':
    put:
      summary: Refund Spendback (Full)
      operationId: put-spendback-spnd_token-refund
      tags:
        - Spend Back
      description: Perform a spendback refund for the full amount.
      security:
        - client Credential Grant Flow:
            - modify
    patch:
      summary: Refund Spendback (Partial)
      operationId: patch-spendback-spnd_token-refund
      tags:
        - Spend Back
      description: Perform a spendback refund for a partial amount. 
      security:
        - client Credential Grant Flow:
            - modify
  '/transfers/{xfer-token}':
    get:
      summary: Retrieve Transfer
      description: Retrieve details of a specific transfer represented by a transfer token.
      operationId: get-transfers-xfer_token
      tags:
        - Transfers
      security:
        - client Credential Grant Flow:
            - read-only
    post:
      summary: Accept Transfer Quote
      description: Accept a transfer quote
      operationId: post-transfers-xfer_token
      tags:
        - Transfers
      security:
        - client Credential Grant Flow:
            - modify
    delete:
      summary: Cancel Transfer Quote
      description: Optional cancellation that auto-cancels after a period organically expires or when account activity invalidates the quote.
      operationId: delete-transfers-xfer_token
      tags:
        - Transfers
      security:
        - client Credential Grant Flow:
            - modify
  '/users/{user-token}':
    put:
      summary: Update User
      description: 'Update a user object (change email, address change, etc.) using a user token.'
      operationId: put-users-user_token
      tags:
        - Users
      security:
        - client Credential Grant Flow:
            - modify
    get:
      summary: Retrieve User
      operationId: get-users-user_token
      description: Retrieve a single user record by user token.
      tags:
        - Users
      security:
        - client Credential Grant Flow:
            - read-only
  '/users/{user-token}/balances':
    get:
      summary: List User Balances
      description: 'Retrieve a list of user balances that supports filtering, sorting, and pagination through existing mechanisms.'
      operationId: get-users-user_token-balances
      tags:
        - Balances
      security:
        - client Credential Grant Flow:
            - read-only
  '/users/{user-token}/bank-accounts':
    get:
      summary: List Bank Accounts
      operationId: get-users-user_token-bankaccounts
      tags:
        - Bank Accounts
      description: 'Retrieve a list of bank accounts that supports filtering, sorting, and pagination through existing mechanisms.'
      security:
        - client Credential Grant Flow:
            - read-only
    post:
      summary: Create Bank Account
      operationId: post-users-user_token-bankaccounts
      tags:
        - Bank Accounts
      description: Create a quote for a bank account using a user token.
      security:
        - client Credential Grant Flow:
            - modify
  '/users/{user-token}/bank-accounts/{dest-token}':
    get:
      summary: Retrieve Bank Account
      operationId: get-users-user_token-bankaccounts-dest_token
      tags:
        - Bank Accounts
      description: 'Retrieve a list of bank accounts using a destination token that supports filtering, sorting, and pagination through existing mechanisms.'
      security:
        - client Credential Grant Flow:
            - read-only
    put:
      summary: Update Bank Account
      operationId: put-users-user_token-bankaccounts-dest_token
      tags:
        - Bank Accounts
      description: Update a bank account.
      security:
        - client Credential Grant Flow:
            - modify
    delete:
      summary: Delete Bank Account
      description: Delete (cloak) a user bank account.
      operationId: delete-users-user_token-bankaccounts-dest_token
      tags:
        - Bank Accounts
      security:
        - client Credential Grant Flow:
            - modify
  '/users/{user-token}/bank-accounts/requirements':
    get:
      summary: Get Bank Account Requirements
      description: 'Retrieve requirements for adding a bank account using the parameters provided (user context, given country of residence, supported EFT provider(s), destination currency, destination country, required fields, with names, and regex validation expression) for easy customer wire-up and validation.'
      operationId: get-users-user_token-bankaccounts-requirements
      tags:
        - Bank Accounts
      security:
        - client Credential Grant Flow:
            - read-only
  '/users/{user-token}/documents':
    get:
      summary: List User Documents
      description: 'Retrieve a list of user documents that supports filtering, sorting, and pagination through existing mechanisms.'
      operationId: get-users-user_token-documents
      tags:
        - Documents
      security:
        - client Credential Grant Flow:
            - read-only
    post:
      summary: Create User Document
      operationId: post-users-user_token-documents
      tags:
        - Documents
      description: Create a quote for a user document.
      security:
        - client Credential Grant Flow:
            - modify
  '/users/{user-token}/documents/{docu-token}':
    get:
      summary: Retrieve User Document
      description: Retrieve an individual user document by its document token.
      operationId: get-users-user_token-documents-docu_token
      tags:
        - Documents
      security:
        - client Credential Grant Flow:
            - read-only
    put:
      summary: Replace User Document
      description: Replace the user document at the given document token.
      operationId: put-users-user_token-documents-docu_token
      tags:
        - Documents
      security:
        - client Credential Grant Flow:
            - modify
  '/users/{user-token}/paperchecks':
    get:
      summary: List Paper Checks
      operationId: get-users-user_token-paper-checks
      tags:
        - Paper Checks
      description: 'Retrieve a list of paper checks that supports filtering, sorting, and pagination through existing mechanisms.'
      security:
        - client Credential Grant Flow:
            - read-only
    post:
      summary: Order Paper Check
      operationId: post-users-user_token-paperchecks
      tags:
        - Paper Checks
      description: Create a quote for a paper check.
      security:
        - client Credential Grant Flow:
            - modify
  '/users/{user-token}/paper-checks/{xfer-token}':
    get:
      summary: Retrieve Paper Check
      operationId: get-users-user_token-paperchecks-dest_token
      tags:
        - Paper Checks
      description: 'Retrieve a list of paper checks by destination token that supports filtering, sorting, and pagination through existing mechanisms.'
      security:
        - client Credential Grant Flow:
            - read-only
    put:
      summary: Update Paper Check
      operationId: put-users-user_token-paperchecks-dest_token
      tags:
        - Paper Checks
      description: Create a quote for a paper check.
      security:
        - client Credential Grant Flow:
            - modify
    delete:
      summary: Cancel Paper Check
      operationId: delete-users-user_token-paper-checks-dest_token
      description: Delete a paper check by destination token.
      tags:
        - Paper Checks
      security:
        - client Credential Grant Flow:
            - modify
  '/users/{user-token}/prepaid-cards/{dest-token}':
    post:
      summary: Replace Prepaid Card
      operationId: post-users-user_token-prepaidcards-dest_token
      tags:
        - Prepaid Cards
      description: Replace an existing Prepaid Card specifying the replacement reason and the card package for the replacement card.
      security:
        - client Credential Grant Flow:
            - modify
    get:
      summary: Retrieve Prepaid Card
      operationId: get-users-user_token-prepaid-cards-dest_token
      description: Retrieve Prepaid Card details by destination token.
      tags:
        - Prepaid Cards
      security:
        - client Credential Grant Flow:
            - read-only
    patch:
      summary: Update Prepaid Card (Partial)
      operationId: patch-users-user_token-prepaidcards-dest_token
      description: Partial Prepaid Card update typically used when modifying card status. <i>*Does not require the entire object be passed in the request</i>
      tags:
        - Prepaid Cards
      security:
        - client Credential Grant Flow:
            - modify
  '/users/{user-token}/prepaid-cards/{dest-token}/balances':
    get:
      summary: List Prepaid Card Balance
      description: 'Retrieve a list of balances by destination token that supports filtering, sorting, and pagination through existing mechanisms. <i>*If the user belongs to a Flex-based program, balances against the user resource will return the wallet balance only. If it is a pre-paid card program (i.e., Meta USD), this balance and its associated pre-paid card balance will be the same.</i>'
      operationId: get-users-user_token-prepaidcards-dest_token-balances
      tags:
        - Balances
      security:
        - client Credential Grant Flow:
            - read-only
  '/users/{user-token}/prepaid-cards/{dest-token}/pin':
    get:
      summary: Generate PIN Operation Token
      description: Retrieve one part of a two-part token required to reveal or set a client side PIN. <i>*Not all programs support a reveal or set PIN operation.</i>
      operationId: get-users-user_token-prepaidcards-dest_token-pin
      tags:
        - Prepaid Cards
      security:
        - client Credential Grant Flow:
            - read-only
    put:
      summary: Set PIN (if supported)
      description: Allows the setting of a PIN if supported by program.
      operationId: put-users-user_token-prepaidcards-dest_token-pin
      tags:
        - Prepaid Cards
      security:
        - client Credential Grant Flow:
            - modify
    post:
      summary: Reveal PIN (if supported)
      operationId: post-users-user_token-prepaid-cards-dest_token-pin
      description: Reveals the PIN for a card where PIN reveal functionality is supported in the program and hosted by PayQuicker.
      tags:
        - Prepaid Cards
      security:
        - client Credential Grant Flow:
            - modify
  '/users/{user-token}/prepaid-cards/{dest-token}/receipts':
    get:
      summary: List Prepaid Card Receipts
      operationId: get-users-user_token-prepaidcards-receipts
      tags:
        - Receipts
      description: 'Retrieve a list all prepaid-card receipts that supports filtering, sorting, and pagination through existing mechanisms.'
      security:
        - client Credential Grant Flow:
            - read-only
  '/users/{user-token}/receipts':
    summary: Receipts
    description: ''
    get:
      description: 'Retrieve a list all user receipts that supports filtering, sorting, and pagination through existing mechanisms.'
      operationId: get-users-receipts
      summary: List User Receipts
      tags:
        - Receipts
      security:
        - client Credential Grant Flow:
            - read-only
  /transfers:
    summary: Transfers
    description: ''
    get:
      summary: List Transfers
      description: 'Retrieve a list of all transfers that supports filtering, sorting, and pagination through existing mechanisms.'
      operationId: get-transfers
      tags:
        - Transfers
      security:
        - client Credential Grant Flow:
            - read-only
    post:
      summary: Quote Transfer
      description: 'Create a new quote. <i>*This can be a non-payment card-to-card transfer, prepaid card from Flex (wallet), bank account, or user-to-user transfer.</i>'
      operationId: post-transfers
      tags:
        - Transfers
      security:
        - client Credential Grant Flow:
            - modify
  '/users/{user-token}/prepaid-cards':
    get:
      summary: List Prepaid Cards
      description: 'Retrieve a list of all pre-paid cards by user token that supports filtering, sorting, and pagination through existing mechanisms.'
      operationId: get-users-user_token-prepaidcards
      tags:
        - Prepaid Cards
      security:
        - client Credential Grant Flow:
            - read-only
    post:
      summary: Order Prepaid Card
      operationId: post-users-user_token-prepaidcards
      tags:
        - Prepaid Cards
      description: 'Order a pre-paid card for the user by specifying a cardPackage. <i>*A package defines the type of card, currency, artwork utilized, and often the method of delivery.</i>'
      security:
        - client Credential Grant Flow:
            - modify
  /spend-back:
    get:
      summary: List Spend Backs
      operationId: get-spendback
      tags:
        - Spend Back
      description: |
        [⭻⭻ Reference](page:working-with-resources/spendbacks#list-spend-backs) Retrieve a list of all spendbacks that supports filtering, sorting, and pagination through existing mechanisms.
      security:
        - client Credential Grant Flow:
            - read-only
    post:
      summary: Quote Spendback
      operationId: post-spendback
      tags:
        - Spend Back
      description: 'Create a spendback quote. <i>*Spendbacks can be automatically accepted by setting the `autoAcceptQuote` flag. If not automatically accepted, a POST is required to the spendback endpoint using the token returned in the response. Quotes can be accepted, cancelled, or allowed to expire.</i>'
      security:
        - client Credential Grant Flow:
            - modify
  /payments:
    get:
      summary: List Payments
      operationId: get-payments
      tags:
        - Payments
      description: 'Retrieve a list of all payments that supports filtering, sorting, and pagination through existing mechanisms.'
      security:
        - client Credential Grant Flow:
            - read-only
    post:
      summary: Create Payment Quote
      operationId: post-payments
      tags:
        - Payments
      description: 'Create a payment quote. '
      security:
        - client Credential Grant Flow:
            - modify
  '/accounts/{acct-token}/balances':
    get:
      summary: List Account Balances
      operationId: get-accounts-acct_token-balances
      description: Retrieve a single account balance.
      tags:
        - Balances
      security:
        - client Credential Grant Flow:
            - read-only
  /users:
    description: 'Everything starts with a user. It is the resource which owns any associated pre-paid cards, bank cards, bank accounts, paper checks, etc. Users can be pre-activated  without email verification required or PayQuicker can host the registration experience. KYC operations will be performed against the user resource even if the KYC requirements are tied to a specific destination token (i.e., PPS GBP Prepaid card, etc.).'
    get:
      security:
        - client Credential Grant Flow:
            - read-only
      summary: List Users
      description: 'Retrieve a list of all users that supports filtering, sorting, and pagination through existing mechanisms.'
      operationId: get-users
      tags:
        - Users
    post:
      security:
        - client Credential Grant Flow:
            - modify
      summary: Create User
      description: 'Create a new user. Payload contains both required and optional fields for user- and company-based users, allowing for the creation of a corporate/partnership/dba (i.e., Grubhub model) user along with a standard end user (i.e., <i>Payee</i>). The type of the user (<i>Business</i> vs. <i>User</i>) and type of business (<i>Corporation</i> vs. <i>Partnership</i>) provide context that impacts KYC etc.'
      operationId: post-users
      tags:
        - Users
  '/users/{user-token}/idv-checks':
    get:
      summary: List User IDV Checks
      tags:
        - Users
      operationId: get-users-user_token-idv-checks
      description: 'Retrieve a list of IDV checks by user token that supports filtering, sorting, and pagination through existing mechanisms.'
      security:
        - client Credential Grant Flow:
            - read-only
  '/users/{user-token}/idv-checks/{idvc-token}':
    get:
      summary: Retrieve User IDV Check
      operationId: get-users-user_token-idv-checks-idvc_token
      description: 'Retrieve a list of all IDV check by IDVC token that supports filtering, sorting, and pagination through existing mechanisms.'
      tags:
        - Users
      security:
        - client Credential Grant Flow:
            - read-only
  /webhooks:
    description: 'Retrieve a list of all webhooks. Webhooks allow the client to be notified of events, such as when a payment has been accepted or a user is awaiting document approval.'
    get:
      summary: List Webhook Subscriptions
      tags:
        - Webhooks
      operationId: get-webhook
      description: 'Retrieve a list of all webhook subscriptions that supports filtering, sorting, and pagination through existing mechanisms.'
      security:
        - client Credential Grant Flow:
            - read-only
    post:
      summary: Create Webhook Subscription
      operationId: post-webhooks
      tags:
        - Webhooks
      description: 'Create a webhook subscription for a given URL and namespace. When this event fires, the webhook receives a call from the API.'
      security:
        - client Credential Grant Flow:
            - modify
  '/webhooks/{webh-token}':
    get:
      summary: Retrieve Webhook Subscription
      tags:
        - Webhooks
      operationId: get-webhooks-webh-token
      description: Retrieve a single webhook subscription using the webhook token.
      security:
        - client Credential Grant Flow:
            - read-only
    delete:
      summary: Delete Webhook Subscription
      operationId: delete-webhooks-webh-token
      description: Delete a webhook subscription. Deleted webhooks no longer receive notifications about events. Deleting an already deleted webhook will result in a successful 200 (OK) response code.
      tags:
        - Webhooks
      security:
        - client Credential Grant Flow:
            - modify
  '/users/{user-token}/events':
    get:
      summary: List User Events
      tags:
        - Users
      operationId: get-users-user_token-events
      description: 'Retrieve a list of all user events that supports filtering, sorting, and pagination through existing mechanisms.'
  '/users/{user-token}/events/{evnt-token}':
    get:
      summary: Retrieve User Event
      tags:
        - Users
      operationId: get-users-user_token-events-event_token
      description: Retrieve a single user event
  /programs:
    get:
      summary: List Programs
      tags:
        - Program
      operationId: get-programs
      description: 'Retrieve a list of all programs that supports filtering, sorting, and pagination through existing mechanisms.'
  '/programs/{prog-token}':
    get:
      summary: Retrieve Program
      tags:
        - Program
      operationId: get-programs-prog_token
      description: Retrieve a single program configuration
  '/programs/{prog-token}/agreements':
    get:
      summary: List Program Agreements
      operationId: get-programs-prog_token-agreements
      description: 'Retrieve a list of all program agreements that supports filtering, sorting, and pagination through existing mechanisms.'
      tags:
        - Program
  '/programs/{prog-token}/agreements/{agmt-token}':
    get:
      summary: Retrieve Program Agreement
      operationId: get-programs-prog_token-agreements-agmt_token
      description: Retrieve a single program agreement
      tags:
        - Program
  '/users/{user-token}/agreements/{agmt-token}':
    post:
      summary: Accept Program Agreement
      operationId: post-users-user_token-agreements-agmt_token
      description: Accept a single program agreement
      tags:
        - Users
  '/users/{user-token}/agreements':
    get:
      summary: List Accepted Program Agreements
      tags:
        - Users
      operationId: get-users-user_token-agreements
      description: 'Retrieve a list of all accepted program agreements that supports filtering, sorting, and pagination through existing mechanisms.'
  '/users/{user-token}/prepaid-cards/{dest-token}/pci':
    get:
      summary: Generate Prepaid Card Data Token
      tags:
        - Prepaid Cards
      operationId: get-users-user-token-prepaid-cards-dest-token-pci
      security:
        - client Credential Grant Flow:
            - read-only
      description: Generate a token used to reveal prepaid card information in the form of image data (base64) or JSON.
    post:
      summary: Get Prepaid Card Data
      operationId: post-users-user-token-prepaid-cards-dest-token-pci
      security:
        - client Credential Grant Flow:
            - write
      description: 'Return prepaid card data in the form of image data, text, or both.'
      tags:
        - Prepaid Cards
components:
  securitySchemes:
    client Credential Grant Flow:
      type: oauth2
      flows:
        clientCredentials:
          tokenUrl: 'https://identity.mypayquicker.build/core/connect/token'
          refreshUrl: ''
          scopes:
            'https://www.payquicker.com/scopes/daybreak/access/base ': ''
            'https://www.payquicker.com/scopes/daybreak/access/partner': ''
            'https://www.payquicker.com/scopes/daybreak/access/public': ''
            read-only: 'Can be accessed, but not modified'
            write: Can be accessed and edited
tags:
  - name: Payments
    description: Payment-related operations
  - name: Transfers
    description: Transfer-related operations
  - name: Spend Back
    description: Spendback-related operations
  - name: Prepaid Cards
    description: Prepaid Card-related operations
  - name: Paper Checks
    description: Paper check-related operations
  - name: Bank Accounts
    description: Bank account-related operations
  - name: Balances
    description: Balance-related operations
  - name: Receipts
    description: Receipt-related operations
  - name: Accounts
    description: Account-related operations
  - name: Users
    description: User-related operations
  - name: Documents
    description: Document-related operations
  - name: IDV
    description: Identity Verification-related operations
  - name: Webhooks
    description: Webhook-related operations
  - name: Program
security:
  - API Key - 1: []
